'⚙️Server':
- packages/backend/**/*

'🖥️Client':
- packages/frontend/**/*

'🧪Test':
- scripts/cypress/**/*
- packages/backend/test/**/*

'‼️ wrong locales':
- any: ['locales/*.yml', '!locales/ja-JP.yml']
